### ISSUE TITLE
Gitignore publishing info

### ISSUE THREAD

**Issue by smoore4moma** [BootCampGuru/LondonCalling#1]
Hello.  You probably want to add an exception to PublishProfiles in your gitignore.  Any web.configs too.   Steve

https://github.com/BootCampGuru/LondonCalling/blob/master/LondonCalling/Properties/PublishProfiles/LondonCalling%20-%20FTP.pubxml

**Comment by BootCampGuru** [comment]
Yes good point! Will update the Londoncalling applications gitignore file in VS.
